In [ ]:
import pandas as pd
import numpy as np

In [ ]:
hw9_score = pd.read_csv("HW9_scores.csv")
print(hw9_score.shape)
hw9_score.head()

(255, 17)

,Name,SID,Email,Total Score,Max Points,Status,Submission ID,Submission Time,Lateness (H:M:S),View Count,Submission Count,1: Q1 (10.0 pts),2: Q2 (10.0 pts),3: Q3 (10.0 pts),4: Q4 (10.0 pts),5: Q5 (10.0 pts),6: Q6 (3.0 pts)
0,Anirud Lappathi,NaN,anirudl2@illinois.edu,34.5,53.0,Graded,284694457.0,2024-11-01 18:46:40 -0500,00:00:00,1.0,1.0,10.0,0.0,6.0,10.0,8.5,0.0
1,Adarsh Krishnan,667535480,adarshk5@illinois.edu,49.0,53.0,Graded,284874176.0,2024-11-02 14:54:27 -0500,00:00:00,1.0,1.0,8.0,10.0,10.0,10.0,9.0,2.0
2,Reid Faistl,671478944,rfaistl2@illinois.edu,47.0,53.0,Graded,285379854.0,2024-11-04 15:01:30 -0600,00:00:00,1.0,1.0,10.0,7.0,10.0,10.0,10.0,0.0
3,Steve Xing,675912171,stevex2@illinois.edu,44.5,53.0,Graded,285412029.0,2024-11-04 16:21:15 -0600,00:00:00,1.0,1.0,10.0,5.0,10.0,10.0,9.5,0.0
4,Zeeshan Bari Khan,NaN,zbkhan2@illinois.edu,49.0,53.0,Graded,285425371.0,2024-11-04 16:55:36 -0600,00:00:00,4.0,2.0,10.0,7.0,10.0,10.0,10.0,2.0

In [ ]:
for index, row in hw9_score.iterrows():
  netid = row["Email"].split("@")[0]
  hw9_score.loc[index, "SID"] = netid
  score_before_ec = row["1: Q1 (10.0 pts)"] + row["2: Q2 (10.0 pts)"] + row["3: Q3 (10.0 pts)"] + row["4: Q4 (10.0 pts)"] + row["5: Q5 (10.0 pts)"]
  hw9_score.loc[index, "Total Score Out of 50"] = score_before_ec
hw9_score["SIS User ID"] = hw9_score["SID"]
hw9_score.head()

,Name,SID,Email,Total Score,Max Points,Status,Submission ID,Submission Time,Lateness (H:M:S),View Count,Submission Count,1: Q1 (10.0 pts),2: Q2 (10.0 pts),3: Q3 (10.0 pts),4: Q4 (10.0 pts),5: Q5 (10.0 pts),6: Q6 (3.0 pts),Total Score Out of 50,SIS User ID
0,Anirud Lappathi,anirudl2,anirudl2@illinois.edu,34.5,53.0,Graded,284694457.0,2024-11-01 18:46:40 -0500,00:00:00,1.0,1.0,10.0,0.0,6.0,10.0,8.5,0.0,34.5,anirudl2
1,Adarsh Krishnan,adarshk5,adarshk5@illinois.edu,49.0,53.0,Graded,284874176.0,2024-11-02 14:54:27 -0500,00:00:00,1.0,1.0,8.0,10.0,10.0,10.0,9.0,2.0,47.0,adarshk5
2,Reid Faistl,rfaistl2,rfaistl2@illinois.edu,47.0,53.0,Graded,285379854.0,2024-11-04 15:01:30 -0600,00:00:00,1.0,1.0,10.0,7.0,10.0,10.0,10.0,0.0,47.0,rfaistl2
3,Steve Xing,stevex2,stevex2@illinois.edu,44.5,53.0,Graded,285412029.0,2024-11-04 16:21:15 -0600,00:00:00,1.0,1.0,10.0,5.0,10.0,10.0,9.5,0.0,44.5,stevex2
4,Zeeshan Bari Khan,zbkhan2,zbkhan2@illinois.edu,49.0,53.0,Graded,285425371.0,2024-11-04 16:55:36 -0600,00:00:00,4.0,2.0,10.0,7.0,10.0,10.0,10.0,2.0,47.0,zbkhan2

In [ ]:
canvas_grade = pd.read_csv("canvas_gradebook.csv")
print(canvas_grade.shape)
canvas_grade.head()
# print(canvas_grade.loc[244, "HW9 (1050916)"])

(245, 111)

,Student,ID,SIS User ID,SIS Login ID,Integration ID,Section,Midterm 1 (1118341),Midterm 1 Curved (1123649),Opt-out form for graded group discussion (1050868),group_id (1050926),...,LecturePolls Current Score,LecturePolls Unposted Current Score,LecturePolls Final Score,LecturePolls Unposted Final Score,Current Points,Final Points,Current Score,Unposted Current Score,Final Score,Unposted Final Score
0,Points Possible,NaN,NaN,NaN,NaN,NaN,150.0,150.0,0.0,0.0,...,(read only),(read only),(read only),(read only),(read only),(read only),(read only),(read only),(read only),(read only)
1,"Ahmed, Zahid",125367.0,zahida2,zahida2,664416733.0,CS 361 ADE Fall 2024 CRN66304 and CS 361 AL1 F...,102.0,107.0,NaN,NaN,...,NaN,NaN,NaN,NaN,543.93,543.93,88.73,88.73,66.49,66.49
2,"Akin, Furkan",396163.0,furkana2,furkana2,654400108.0,CS 361 ADC Fall 2024 CRN66307 and CS 361 AL1 F...,119.0,124.0,NaN,NaN,...,NaN,NaN,NaN,NaN,606.55,606.55,98.31,98.31,74.15,74.15
3,"Alexander, Aaron",10122.0,aalex9,aalex9,663030982.0,CS 361 ADH Fall 2024 CRN76054 and CS 361 AL1 F...,79.0,84.0,NaN,NaN,...,NaN,NaN,NaN,NaN,439.35,439.35,72.02,72.02,53.71,53.71
4,"Alkhayyat, Yousif",368311.0,yalkh3,yalkh3,661122220.0,CS 361 ADB Fall 2024 CRN66306 and CS 361 AL1 F...,116.0,121.0,0.0,NaN,...,NaN,NaN,NaN,NaN,337.83,337.83,60.00,60.00,41.30,41.30

In [ ]:
# print(hw9_score["Total Score"][0])
for index, row in canvas_grade.iterrows():
  if (index != 0 and index != canvas_grade.shape[0] - 1):
    netid = canvas_grade["SIS User ID"][index]
    # print("Netid: " + str(netid))
    score = hw9_score[hw9_score["SIS User ID"] == netid]["Total Score Out of 50"]
    if not score.empty:
      # print(score)
      # print("Score: " + str(score.iloc[0]))
      canvas_grade.loc[index, "HW9 (1050916)"] = score.iloc[0]

canvas_grade.head()
# print(canvas_grade.loc[244, "HW9 (1050916)"])

,Student,ID,SIS User ID,SIS Login ID,Integration ID,Section,Midterm 1 (1118341),Midterm 1 Curved (1123649),Opt-out form for graded group discussion (1050868),group_id (1050926),...,LecturePolls Current Score,LecturePolls Unposted Current Score,LecturePolls Final Score,LecturePolls Unposted Final Score,Current Points,Final Points,Current Score,Unposted Current Score,Final Score,Unposted Final Score
0,Points Possible,NaN,NaN,NaN,NaN,NaN,150.0,150.0,0.0,0.0,...,(read only),(read only),(read only),(read only),(read only),(read only),(read only),(read only),(read only),(read only)
1,"Ahmed, Zahid",125367.0,zahida2,zahida2,664416733.0,CS 361 ADE Fall 2024 CRN66304 and CS 361 AL1 F...,102.0,107.0,NaN,NaN,...,NaN,NaN,NaN,NaN,543.93,543.93,88.73,88.73,66.49,66.49
2,"Akin, Furkan",396163.0,furkana2,furkana2,654400108.0,CS 361 ADC Fall 2024 CRN66307 and CS 361 AL1 F...,119.0,124.0,NaN,NaN,...,NaN,NaN,NaN,NaN,606.55,606.55,98.31,98.31,74.15,74.15
3,"Alexander, Aaron",10122.0,aalex9,aalex9,663030982.0,CS 361 ADH Fall 2024 CRN76054 and CS 361 AL1 F...,79.0,84.0,NaN,NaN,...,NaN,NaN,NaN,NaN,439.35,439.35,72.02,72.02,53.71,53.71
4,"Alkhayyat, Yousif",368311.0,yalkh3,yalkh3,661122220.0,CS 361 ADB Fall 2024 CRN66306 and CS 361 AL1 F...,116.0,121.0,0.0,NaN,...,NaN,NaN,NaN,NaN,337.83,337.83,60.00,60.00,41.30,41.30

In [ ]:
canvas_grade["HW9 (1050916)"]
canvas_grade.loc[:canvas_grade.shape[0] - 2, "HW9 (1050916)"] = canvas_grade.loc[:canvas_grade.shape[0] - 2, "HW9 (1050916)"].fillna(0.0)

canvas_grade["HW9 (1050916)"]

0      50.0
1      43.5
2       0.0
3       0.0
4      50.0
       ...
240     0.0
241    48.0
242    47.0
243    49.0
244     NaN
Name: HW9 (1050916), Length: 245, dtype: float64

In [ ]:
canvas_grade.to_csv("Grades-CS361.csv")